[multipage-level=2]
== Data mobilization 

=== Planning
[NOTE.objectives]
In the planning module, you will review key project planning stages and will learn how to create a viable workflow. Additionally, you will create an idealized project plan/workflow based on Use Case I. You will identify goals, tasks, key stakeholders and roles and will assign specific tasks to stages.

==== Resourcing and organizing
[NOTE.presentation]
Watch two videos on resourcing and organizing a mobilization project.

.In this video (15:09), you will learn how to define the elements that will have an impact on a project and will look at the interactions between the elements. If you are unable to watch the embeded Vimeo video, you can download it locally. (MP4 - 25.1 MB)
video::438517096[vimeo, height=480, width=640, align=center]

.This video (15:52) focuses on tasks and the ways that they can be organized
in order to prepare practicle workable plans and clear documentation. If you are unable to watch the embeded Vimeo video, you can download it locally. (MP4 - 26.2 MB)
video::438516869[vimeo, height=480, width=640, align=center]

==== Use Case I
[NOTE.activity]
Familiarize yourself with the use case story.

Use Case I is a practice use case for section 200. It is recommended that you download the exercise sheet (MS Word, 829.7 KB) so that you can make notes as you work through the exercises. Suggested solutions will be provided in the forums after each section is complete and discussed during the live Zoom sessions. Use Case I is not graded. The use case will open in another window.

==== Exercises 1a-c: Planning a project
[NOTE.activity]
For this activity, you will be using a virtual tabletop platform and making notes on your Use Case I answer sheet for exercise 1 a-c. Review the exercise instructions below.

*References*

* Role definitions
* Stage definitions

To help you to work through the planning exercises for Use Case's 2 and 3, we have made available five virtual playing card tables.

Because these are shared spaces, we ask that you follow these rules so that everyone who wants to use them can:

. Clean up after yourself. If you use a card table, please be sure to return it to it's clean and original state when you are done. This means putting all of the cards away and removing/deleting any new cards that you have added to the deck. You can do this by clicking the recall buttons below each deck of cards.
. If it's busy, try another table. If you see that a card table is in use, please use one of the other card table links. If you are unable to find an empty card table, please use the eLearning platform's Forum to request time on a table and alert the trainers so that we can check the tables to be sure that any tables were not left unattended (or if we need to create an additional table for you).
. Don't leave a table unattended. Please do not leave your work on a table sitting out for long periods of time. If you need to step away for an hour or two, that is acceptable, but please do not leave the cards unattended for more than 4 hours. If you need to leave your set up for an extended period of time, please use the eLearning platform to notify the group and trainers which link you are using, why you need to leave your cards, and when you will return to complete your work.
. Take screen captures often. We cannot guarantee that your cards will not be reset accidentally by someone from the  workshop or by someone from your own project. You cannot reset the cards once they have been recalled and reset. If you want to submit a screenshot with your excercise please do.
. The trainers reserve the right to reset the card tables. If we observe that one or more tables contain cards that have not been put away and have not been used for more than four hours without any notifications in the Forum on the eLearning platform, we will clear and reset the table for others to use.

Gameroom links:

RED: http://playingcards.io/sca368
GREEN: http://playingcards.io/fxkceg
YELLOW: http://playingcards.io/7va9m5
BLUE: http://playingcards.io/s6vvn9
PURPLE: http://playingcards.io/tm5g4c

Much appreciation and thanks to Jwalant Patel and Eric Ma for finding and helping to create the online playing tables and Kate Webbink for artistic expertise. The online tabletop platform is provided by PlayingCards.io.

===== Exercise 1: Planning a mobilization project

Download (MS Word, 829.7 KB) and read USE CASE I (if you haven't already).

====== Exercise 1a:

Using the cards select the goals that mostly closely match those the project outlines and then choose the tasks that would need to be carried out to complete them. Next, identify the people/resources that the project has available to it and assign role cards to them as appropriate. Lastly, assign these to their stakeholder groups and affiliations.

. Review the GOALS cards with the group, select and lay out the ones that fit the use case.
. Review the TASK cards with the group.
. Assign the TASK cards to each of the GOAL cards selected from the use case description.
. Identify the institutions and people mentioned in the use case text and make note of them.
. Lay out the AFFILIATIONS cards on the table.
. Review the STAKEHOLDER cards, identify any mentioned in the use case and then decide which AFFILIATION they belong to.
. Review the ROLE cards, identify any mentioned in the use case and decide which STAKEHOLDER group they belong to.
. Make notes to cards as appropriate.
. Once the cards are assigned take pictures and complete your exercise sheet.

====
*Question*

* Are there resources or goals missing from the cards that you feel are critical to the successful completion of the project? Note these on the answer sheet.
====

====== Exercise 1b:

Using the stakeholder and goal analysis from exercise 1a, develop a workflow using the  STAGE cards.

. Re-read the use case introduction, if necessary.
. Decide which TASKS for which each ROLE will be responsible.
. Review the STAGE cards and order the TASKS appropriately.
. Once the cards are assigned complete the answer sheet.

====
*Questions*   

* Are there obvious bottlenecks in the workflow? For example: Are there too many tasks for a particular role/resource?
* What issues do you think would be important to the successful mobilization of data from the points of view of each stakeholder/role? For example: What are the deliverables? Thinking about the general project timeframe, are they realistic?
* Consolidate notes and prioritize in order of importance.
* If you have time you can explore different combinations as different scenarios are possible in different contexts or even try to document the situation for your own project.
====

====
This section should be used when the course is taught virtually or onsite as a group activity.

====== Exercise 1c: After the exercises the presenter of each group will:

. Present any missing stakeholders and/or tasks saying why they were added.
. Highlight the two most critical issues/topics that the group has identified.

Potential discussion points across groups: 
* What similarities and differences can be seen in the flows? 
* Were there common issues that came up across the groups?
====

=== Data capture

==== Foundations: Standards and Darwin Core

==== Data orgins and types

==== Quiz: Data types

==== Data capture, processing and quality

==== Exercise 2: Data capture

=== Data management

==== Principles of data cleaning

==== Exercise 3a: Validation checks

==== Exercise 3b: Tools

==== Exercise 3c: OpenRefine

=== Data publishing

==== Data publishing concepts

==== Demonstration: IPT

==== Exercise 4: IPT
