[multipage-level=2]

== Assessment and certification
[NOTE.objectives]
In this module, you will review the criteria to be used to assess assignments and to achieve certification.

Upon successful completion of the course and successful assessment of assignments (by trainers and mentors), participants have the opportunity to receive an official certification in the form of a Mozilla Open Badge.

* An overall score of 2.5-2.9 earns a BASIC Biodiversity Data Mobilization badge

* An overall score of 3.0-4.0 earns an ADVANCED Biodiversity Data Mobilization badge

Participants are required to submit Use Case 2 (choice between two options) and Use Case 3 and each Use Case is scored against the educational rubrics for the course. The rubrics define the skills and performance levels on which the learning objectives for the course are built.

Review the rubrics to ensure understanding of the skills that will be assessed for certification.

=== Rubric 1

*Planning*

[cols=5*,options="header,footer"]
|===
|Skills
|Beginning performance
1
|Developing performance
2
|Accomplished performance
3
|Outstanding performance
4

|A
|Item
|Item
|Item
|Item

|B
|Item
|Item
|Item
|Item

|C
|Item
|Item
|Item
|Item

|D
|Item
|Item
|Item
|Item
|===

=== Rubric 2

*Data capture*

[options="header,footer"]
|===
|Skills|Performance
||Beginning - 1|Developing - 2|Accomplished - 3|Outstanding - 4
|A|Item|Item|Item|Item
|B|Item|Item|Item|Item
|C|Item|Item|Item|Item
|D|Item|Item|Item|Item
|===

=== Rubric 3

*Data management*

[options="header,footer"]
|===
|Skills|Performance
||Beginning - 1|Developing - 2|Accomplished - 3|Outstanding - 4
|A|Item|Item|Item|Item
|B|Item|Item|Item|Item
|C|Item|Item|Item|Item
|D|Item|Item|Item|Item
|===

=== Rubric 4

*Data publishing*

[options="header,footer"]
|===
|Skills|Performance
||Beginning - 1|Developing - 2|Accomplished - 3|Outstanding - 4
|A|Item|Item|Item|Item
|B|Item|Item|Item|Item
|C|Item|Item|Item|Item
|D|Item|Item|Item|Item
|===

=== Badge recipients

==== Advanced

==== Basic
