== Final assignments

[NOTE.assignments]
For your final activities, you will complete and submit Use Case II and Use Case III for evaluation.

=== USE CASE II
There are two options for USE CASE II (<<use-case-ii-invasive-species,Invasive species>> OR <<use-case-ii-lepidoptera-sightings,Lepidoptera sightings>>).
You only need to select one of them for your assignment.

Required files for submission:

* completed exercise sheet (MS Word Doc or similar is acceptable)
* data capture spreadsheet (MS Excel, csv, txt or similar is acceptable)
* cleaned/standardized dataset (MS Excel, csv, txt or similar is acceptable)

=== USE CASE III
There is only one option for USE CASE III (<<use-case-iii-birds-from-literature,Birds from literature>>).

Required files for submission:

* completed exercise sheet (MS Word Doc or similar is acceptable)
* data capture spreadsheet (MS Excel, csv, txt or similar is acceptable)
* cleaned/standardized dataset (MS Excel, csv, txt or similar is acceptable)

IMPORTANT: Include the use case and exercise number along with your name on all files submitted. For example, Russell-UC2-IS-exercise-sheet.docx, Russell-UC2-IS-2.xlsx, Russell-UC2-IS-3.xlsx. *All files must be submitted in English*. Contact training@gbif.org if you have any questions.

=== Assignment submission

ifdef::backend-pdf[]
Assignments can be submitted from the online (HTML) version of the course.
endif::backend-pdf[]

ifndef::backend-pdf[]
Please submit your assignment files using the form below.  If you do not see a form, you can also visit the https://gbif.app.box.com/f/1e44182c4bc74d659082c0e952d83e80[submission site^] in a new window.

++++
<iframe src="https://gbif.app.box.com/f/1e44182c4bc74d659082c0e952d83e80" style="width: 100%; min-height: 900px;"></iframe>
++++
endif::backend-pdf[]
