== Data capture
[NOTE.objectives]
In this module, you will learn about the concept of standards, in particular, the Darwin Core standard and its components. You will also learn the types of primary biodiversity data and how to best share that information within GBIF. Lastly, you will review principles of data quality in the context of data capture and will learn about data quality and coherence (especially on subjects such as georeferencing, dates, names and taxa cross-checking).

=== Foundations: Standards and Darwin Core
[NOTE.presentation]
Watch a video introduction to standards and Darwin Core

.In this video (15:37), you will learn how you interact with standards every day. Then you will be introduced to biodiversity information standards, including the Darwin Core Standard with which you will continue to use throughout this course. If you are unable to watch the embeded Vimeo video, you can download it locally. (MP4 - 27 MB)
video::439983725[vimeo, height=480, width=640, align=center]

=== Data orgins and types
[NOTE.presentation]
Watch a video on Biodiversity data origins and types

.In this video (10:45), you will review primary biodiversity data that can be shared within GBIF. If you are unable to watch the embeded Vimeo video, you can download it locally. (MP4 - 19 MB)
video::438251559[vimeo, height=480, width=640, align=center]

====
*Questions*
* Is your data type different than you originally thought?
* With what kind of data do you work?
* How would you publish your data to GBIF (using which Core and/or extension)?
====

=== Data capture, processing and quality
[NOTE.presentation]
Watch a video on data capture, processing and quality

.In this video (09:11), you will explore the principles of data quality applied to data capture, specifically when capturing data from collection labels, fieldwork notebooks, spreadsheets, etc. If you are unable to watch the embeded Vimeo video, you can download it locally. (MP4 - 19 MB)
video::438251371[vimeo, height=480, width=640, align=center]

=== Exercise 2
[NOTE.activity]
For this activity, you will complete an exercise simulating data capture. You will begin to work with Darwin Core terms and make decisions on data that is needed for your organization/project and you will consider which of that data will be shared later during publication.

Refer to USE CASE 1, exercise 2 for further details.

Imagine that you are the person assigned to transcribe the data found on the herbarium sheets.

. Download the herbarium sheets: ‘USE CASE 1 - Exercise 2 Base Material.zip’. (34.4 MB).
There are 10 images. Two images per specimen for a total of five specimens. 
The herbarium sheets are in Spanish (data may come to you in various means and in other languages than your own), but you should be able to recognize the data contained in the fields on the labels. 
Remember to use both images per record to compile the information.
. Download the spreadsheet template:  ‘USE CASE 1 - Exercise 2 - Template (Occurrences).xlsx’ (57.3 KB) to transcribe the information found on each of the images for the five specimens. NOTE: you may need to add fields to the spreadsheet as you may be able to capture more information from the labels that was planned for in the template.
. Use the exercise sheet at the end of Use Case I (829.7 KB) to note your answers.

=== Review
