== Colophon

=== Suggested citation

GBIF Secretariat (2021) GBIF Biodiversity Data Mobilization Course. 11th edition. GBIF Secretariat: Copenhagen. https://doi.org/10.35035/ce-c6cr-6w42. [Date of course.]

=== Contributors

The _GBIF Biodiversity Data Mobilization Course_ was originally developed as part of https://www.gbif.org/bid[Biodiversity Information Development^], a programme funded by the https://europa.eu[European Union^]. The original curriculum was created by Nestor Beltran, Sharon Grant, Nicolas Nóe, Sophie Pamerlon, Alberto Gonzalez Talavan, Mélainie Raymond, Laura Anne Russell and Katia Cezón, with additional contributions by GBIF trainers, mentors and students.

=== Licence

_GBIF Biodiversity Data Mobilization Course_ is licensed under https://creativecommons.org/licenses/by-sa/4.0[Creative Commons Attribution-ShareAlike 4.0 Unported License].

=== Persistent URI

https://doi.org/10.35035/ce-c6cr-6w42

=== Document control

11th edition, Feb 2021

=== Cover image

// Caption. Credit, source, licence.
Elegant Grasshopper (_Zonocerus elegans_), Bulawayo, Zimbabwe. 
Photo 2021 nickypegg via https://www.gbif.org/occurrence/3018014153[iNaturalist research-grade observations], licensed under http://creativecommons.org/licenses/by-nc/4.0/[CC BY-NC 4.0].
