[description]
== Course description

****
This course enables participants to plan and implement biodiversity data mobilization efforts effectively using accepted community standards. 
Its aim is to increase the volume, richness and quality of the data published through the GBIF network. 
This course was first developed as part of the https://www.gbif.org/programme/82243/bid-biodiversity-information-for-development[Biodiversity Information for Development] (BID) programme funded by the https://europa.eu/[European Union].

Topics include:

* Project management
* Data capture
* Data management
* Data publishing

This course is comprised of video instruction paired with quizzes and practical exercises. 
When offered as an onsite or virtual workshop, group work and social interaction are encouraged.
****

=== Audience

This course is designed for individuals who work as researchers or technicians in biodiversity research or policy institutions. 
The instruction provided is particularly useful for those who have a need or desire to plan mobilization projects and/or mobilize biodiversity information for their respective institutions.

=== Prerequisites

. Introduction to GBIF course

. Additionally, to make best use of the activities around this course, the participants should possess the following skills and knowledge:

* Basic skills in computer and internet use, and, in particular, in the use of spreadsheets.
* Basic knowledge about geography and biodiversity informatics: geography and mapping concepts, basic taxonomy and nomenclature rules.
* Willingness to disseminate the knowledge learned in the workshop with partners and collaborators in your project by adapting the biodiversity data mobilization training materials to specific contexts and languages while maintaining their instructional value.
* A good command of English. While efforts are made to provide materials in other languages, instruction/videos will be in English.

=== Learning objectives

* Learn key concepts (foundations) of biodiversity informatics, particular to biodiversity digital data management.
* Receive an introduction to the Darwin Core Standard and its components.
* Learn to understand the different stages for planning a mobilization project and how to adapt stages to a specific project.
* Evaluate a data mobilization strategy to identify potential gaps, inefficiencies and pitfalls.
* Develop a data mobilization strategy customized to a given institutional framework.
* Learn to identify the types of data and how to best capture relevant information using best practices, existing softwares, tools and techniques.
* Use software tools designed to facilitate biodiversity data capture to produce digital biodiversity data from analogue sources.
* Learn data quality concepts and receive an introduction to tools used for standardizing data, validating data, and cleaning data.
* Use software tools to evaluate the fitness-for-use of a biodiversity dataset
* Use software tools designed for (biodiversity) data cleaning.
* Learn the process of making biodiversity data freely available online, also known as data publishing, utilizing GBIF’s Integrated Publishing Toolkit (IPT).
* Define the publishable data types and subtypes (if any) for a biodiversity dataset.
* Use the GBIF IPT to publish biodiversity datasets using the appropriate extensions.
* Capacitate others in the planning, capture, management and publishing of biodiversity data.

=== Certification

Upon successful completion of the course and successful assessment of assignments (by trainers and mentors), participants have the opportunity to receive an official certification in the form of an https://openbadges.org/[Open Badge]. 
See <<assessment-and-certification,Assessment and Certification>> for more details.
