== Files for download

All files for the course may be downloaded from this page. 
Or if you prefer, all files are linked individually throughout the course as they occur in the curriculum. 
The video files are embedded throughout the course, as well, and play from YouTube. Subtitles are available when playing from YouTube for most videos. 
If you have difficulty accessing the embedded videos, please download the mp4 files to play them locally on your computer.

=== Videos
The videos are narrated in English. Subtitles are not available for the downloaded videos.

link:../videos/Foundations1.zip[Foundations1.zip,opts=download]
link:../videos/Foundations2.zip[Foundations2.zip,opts=download]
link:../videos/Planning.zip[Planning.zip,opts=download]
link:../videos/Capture.zip[Capture.zip,opts=download]
Management.zip
Publishing.zip
link:../videos/Appendix-Data-Papers.zip.zip[Appendix-Data-Papers.zip,opts=download]

=== Exercise data
This link:../exercise-data/UseCaseExerciseData.zip[compressed file,opts=download] (ZIP 37.7 MB) contains the exercise data for all the use cases. 

=== Exercise sheets
This link:../course-docs/ExerciseSheets.zip[compressed file,opts=download] (ZIP 1.4 MB) contains the exercise sheets for all the use cases. 
The exercises sheets are written in English and should be completed in English.
