[multipage-level=2]

== Data publishing
[NOTE.objectives]
In this module, you will learn about data publishing concepts, including the IPT, cores and extensions, and the importance of licenses, metadata, mandatory fields and hosting of datasets.

=== Data publishing concepts
[NOTE.presentation]
In this video (11:45), you will learn about data publishing concepts and will receive an introduction to the Integrated Publishing Toolkit (https://www.gbif.org/ipt[IPT^]).
If you are unable to watch the embedded video, you can link:../videos/Data_publishing_concepts.mp4[download^,opts=download] it locally. (MP4 - 20 MB)

video::b9O0d9ukjSQ[youtube,height=540,width=960,align=center]

=== IPT overview
[NOTE.presentation]
In this video (??:??), you will receive and overview of the IPT data publishing interface.
If you are unable to watch the embedded video, you can download it locally. (MP4 - ??.?? MB)

video::xxxxxxxx[youtube,height=540,width=960,align=center]

==== Training IPT installations

If you have not already been provided a login, please contact training@gbif.org and you will be provided with a login and password on the course IPT.

https://training-ipt-a.gbif.org/[^]

https://training-ipt-b.gbif.org/[^]

https://training-ipt-c.gbif.org/[^]

=== IPT demonstration
[NOTE.presentation]
In this video (24:16), you will learn how to publish an occurrence dataset using an IPT.
If you are unable to watch the embedded video, you can link:../videos/IPT_demo.mp4[download^,opts=download] it locally. (MP4 - 52.6 MB)

video::eDH9IoTrMVE[youtube,height=540,width=960,align=center]

=== Exercise 4
[NOTE.activity]
In this exercise, you will publish an occurrence dataset using the IPT.

Read <<scenario,USE CASE I>> (if you haven't already).

*Data publishing*

After cleaning the data in the Poales dataset, the team considers that publishing the data online through the GBIF network could be a good way to make this effort visible. You have been requested to lead that publishing work, based on the dataset.

. At this point, you need an account on one of the <<Training IPT installations,course IPTs>>. 
If you have not already been provided a login, please contact training@gbif.org and you will be provided with a login and password on one of the course IPTs.
. Download link:../exercise-data/UC1-4-poales-publishing.csv[UC1-4-poales-publishing.csv,opts=download]. (233.5 KB)
. Use the assigned IPT installation and publish this file.
. Use the previously downloaded exercise sheet to provide your answers.

=== Review

[NOTE.quiz]
Quiz yourself on the concepts learned in this section.

// Note the lack of empty lines between the end of the question (....) and the start of the next question
// (. What…) is required, so I have added // comments to help separate them.
// The + connects the question into the numbered list item, see https://docs.asciidoctor.org/asciidoc/latest/lists/continuation/

****
// Question 1
. What does data publishing mean in the context of GBIF?
+
[question, mc]
....

- [ ] Exporting a csv file of your cleaned data that you can share with your colleagues
- [ ] Writing an article describing your data, and the protocol(s) you used to collect, capture and clean them
- [x] Making your biodiversity dataset(s) publicly accessible and discoverable in a standardized format
....
// Question 2
. What is an IPT?
+
[question, mc]
....

- [ ] a tool that helps you manage & correct your data
- [x] a tool that helps you publish your data to GBIF
- [x] a tool that helps you produce a Data paper
....
// Question 3
. Which Creative Commons licences and waivers are recommended by GBIF for data publication?
+
[question, mc]
....

- [ ] CC-BY, CC-BY-SA and CC-BY-ND
- [x] CC0, CC-BY and CC-BY-NC
- [ ] CC0, CC-BY and CC-BY-SA
....
// Question 4
. What are the three Cores from which you can choose for an IPT resource?
+
[question, mc]
....

- [ ] Metadata Core, Occurrence Core, Multimedia Core
- [ ] Taxon Core, Collection Core, MeasurementOrFact Core
- [x] Occurrence Core, Taxon Core, Event Core
....
// Question 5
. How many Extensions files can a dataset have?
+
[question, mc]
....

- [ ] zero
- [ ] one
- [x] as many as needed
....
****
